######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 5 23:47:41 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ClientSocket.hpp
SOURCES += ClientSocket.cpp Main.cpp
QT += network
